#ifndef OPENEPICENTRE_BACKENDUBUNTU_CLIB_OPENEPICENTRE_STRUCT_USER_OUTPUT_H
#define OPENEPICENTRE_BACKENDUBUNTU_CLIB_OPENEPICENTRE_STRUCT_USER_OUTPUT_H
#include "praise_sets/CLIB_OpenEpiCentre_STRUCT_Output_praise0.h"
#include "praise_sets/CLIB_OpenEpiCentre_STRUCT_Output_praise1.h"
#include "praise_sets/CLIB_OpenEpiCentre_STRUCT_Output_praise2.h"
#include "praise_sets/CLIB_OpenEpiCentre_STRUCT_Output_praise3.h"
#include <list>
namespace CLIBOpenEpiCentre {
	struct CLIB_OpenEpiCentre_STRUCT_User_Output {
	public:
		class Object* dyn_CLASS_get_CLIB_OpenEpiCentre_STRUCT_UserOutput_Item_On_List_Of_ptr_PraiseOutputSubsets(unsigned long long praiseId);
		void dyn_REG_boot1_DEFINE_CLIB_OpenEpiCentre_STRUCT_UserOutput();
		void dyn_REG_boot2_SUBSTANTIATE_CLIB_OpenEpiCentre_STRUCT_UserOutput();
		void dyn_REG_boot3_INITIALISE_CLIB_OpenEpiCentre_STRUCT_UserOutput();
		void dyn_REG_boot4_INSTANTIATE_CLIB_OpenEpiCentre_STRUCT_UserOutput();
		static void stat_CLASS_boot0_DECLARE_CLIB_OpenEpiCentre_STRUCT_UserOutput();
		static void stat_CLASS_boot1_DEFINE_CLIB_OpenEpiCentre_STRUCT_UserOutput();
		static void stat_CLASS_boot3_INITIALISE_CLIB_OpenEpiCentre_STRUCT_UserOutput();
		static void stat_CLASS_boot4_INSTANTIATE_CLIB_OpenEpiCentre_STRUCT_UserOutput();
		static void stat_REG_boot0_DECLARE_CLIB_OpenEpiCentre_STRUCT_UserOutput();
	private:
		static CLIB_OpenEpiCentre_STRUCT_Output_praise0* _stat_CLASS_ptr_CLIB_OpenEpiCentre_STRUCT_UserOutput_Output_praise0;
		static CLIB_OpenEpiCentre_STRUCT_Output_praise1* _stat_CLASS_ptr_CLIB_OpenEpiCentre_STRUCT_UserOutput_Output_praise1;
		static CLIB_OpenEpiCentre_STRUCT_Output_praise2* _stat_CLASS_ptr_CLIB_OpenEpiCentre_STRUCT_UserOutput_Output_praise2;
		static CLIB_OpenEpiCentre_STRUCT_Output_praise3* _stat_CLASS_ptr_CLIB_OpenEpiCentre_STRUCT_UserOutput_Output_praise3;
		static void stat_CLASS_boot1_DEFINE_CLIB_OpenEpiCentre_STRUCT_UserOutput_Outputpraise0();
		static void stat_CLASS_boot1_DEFINE_CLIB_OpenEpiCentre_STRUCT_UserOutput_Output_praise1();
		static void stat_CLASS_boot1_DEFINE_CLIB_OpenEpiCentre_STRUCT_UserOutput_Output_praise2();
		static void stat_CLASS_boot1_DEFINE_CLIB_OpenEpiCentre_STRUCT_UserOutput_Output_praise3();
		static void stat_CLASS_boot3_INITIALISE_CLIB_OpenEpiCentre_STRUCT_UserOutput_Output_praise0();
		static void stat_CLASS_boot3_INITIALISE_CLIB_OpenEpiCentre_STRUCT_UserOutput_Output_praise1();
		static void stat_CLASS_boot3_INITIALISE_CLIB_OpenEpiCentre_STRUCT_UserOutput_Output_praise2();
		static void stat_CLASS_boot3_INITIALISE_CLIB_OpenEpiCentre_STRUCT_UserOutput_Output_praise3();
		static CLIB_OpenEpiCentre_STRUCT_Output_praise0* stat_CLASS_get_ptr_CLIB_OpenEpiCentre_STRUCT_UserOutput_Output_praise0();
		static CLIB_OpenEpiCentre_STRUCT_Output_praise1* stat_CLASS_get_ptr_CLIB_OpenEpiCentre_STRUCT_UserOutput_Output_praise1();
		static CLIB_OpenEpiCentre_STRUCT_Output_praise2* stat_CLASS_get_ptr_CLIB_OpenEpiCentre_STRUCT_UserOutput_Output_praise2();
		static CLIB_OpenEpiCentre_STRUCT_Output_praise3* stat_CLASS_get_ptr_CLIB_OpenEpiCentre_STRUCT_UserOutput_Output_praise3();
	};
}
#endif